### ISSUE TITLE
gfycat.com shutdown affecting your tutorial on codrops

### ISSUE THREAD

**Issue by dhhepting** [lorenzocadamuro/apple-fifth-avenue#22]
I found all the missing videos from your article on codrops using the wayback machine. Would you consider updating your article or posting a new version with updated links to your video content?

**Comment by crnacura** [comment]
Thank you for the heads up @dhhepting! Will take care of this asap.

**Comment by crnacura** [comment]
All videos are now replaced. Thanks again!
